[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
renderer_check = "Mali-G52"
include = [
    "dEQP-VK.pipeline.blend.*",
    "dEQP-VK.api.copy_and_blit.core.*",
]
