[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = [ "/deqp/mustpass/gles2-master.txt" ]
tests_per_group = 250
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [ "/deqp/mustpass/gles2-khr-master.txt" ]
tests_per_group = 250
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
