.radeonsi-stoney-test:amd64:
  extends:
    - .radeonsi-rules
  variables:
    DEVICE_TYPE: hp-11A-G6-EE-grunt
    DTB: ""
    GPU_VERSION: radeonsi-stoney
    BOOT_METHOD: depthcharge
    KERNEL_IMAGE_TYPE: ""
    DRIVER_NAME: radeonsi
    ENV_VARS: "DEQP_PARALLEL=4 DEQP_EXPECTED_RENDERER=STONEY"
  tags:
    - mesa-ci-aarch64-lava-collabora

.radeonsi-stoney-deqp:amd64:
  extends:
    - .lava-test:amd64
    - .radeonsi-stoney-test:amd64

radeonsi-stoney-gles2:amd64:
  extends:
    - .radeonsi-stoney-deqp:amd64
  variables:
    DEQP_VERSION: gles2

# Run two jobs in parallel each running 1/4th of the test suite
radeonsi-stoney-gles3:amd64:
  extends:
    - .radeonsi-stoney-deqp:amd64
  parallel: 2
  variables:
    DEQP_VERSION: gles3
    ENV_VARS: "DEQP_PARALLEL=4 DEQP_EXPECTED_RENDERER=STONEY DEQP_FRACTION=2"

# Run two jobs in parallel each running 1/4th of the test suite
radeonsi-stoney-gles31:amd64:
  extends:
    - .radeonsi-stoney-deqp:amd64
  parallel: 2
  variables:
    DEQP_VERSION: gles31
    ENV_VARS: "DEQP_PARALLEL=4 DEQP_EXPECTED_RENDERER=STONEY DEQP_FRACTION=2"

radeonsi-stoney-traces:amd64:
  extends:
    - .lava-piglit-traces:amd64
    - .radeonsi-stoney-test:amd64
  variables:
    ENV_VARS: "EGL_PLATFORM=surfaceless PIGLIT_PROFILES=replay PIGLIT_JUNIT_RESULTS=1"
  tags:
    - mesa-ci-aarch64-lava-collabora

radeonsi-stoney-piglit-gl:amd64:
  extends:
    - .lava-piglit:amd64
    - .radeonsi-stoney-test:amd64
  variables:
    ENV_VARS: "PIGLIT_FRACTION=4 PIGLIT_PLATFORM=mixed_glx_egl PIGLIT_PROFILES=quick_gl PIGLIT_JUNIT_RESULTS=1 LAVA_START_XORG=1"
